name: 🛠️️ Bug report
description: Does something need fixed?
title: "[BUG]: "
labels: ["Type: Bug"]
body:
  - type: markdown
    attributes:
      value: |
        To report a bug, complete the form below.
  - type: textarea
    attributes:
      label: Description
      description: Detailed description of the bug
    validations:
      required: true
  - type: textarea
    attributes:
      label: Environment
      description: Details of the environment which experienced this issue. e.g., IP address/location, OS, software version, etc.
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Can provide links to a live example, code snippets, screenshots, or other steps to reproduce this issue
  - type: textarea
    attributes:
      label: Possible solution
      description: Possible solution/fix for this issue